"token"="ODg4NDUwNTIyNDg1NTEwMTY0.YUS4Bw.KeUrMZ4GEUTRJFFP5WVTR_jg7hE" # the bot's token
"prefix"="?" # prefix used to denote commands

[music]
# Options for the music commands
"max_volume"=250 # Max audio volume. Set to -1 for unlimited.
[hub]
"category_id"=910433640364781598 # The category where the vc are going to be created.
"hub_vc_id"=910433688578297866 # The hub id.
