version: '3'

services:
  # Discord Bot Service
  nano-bot:
    build:
      context: .  # Path to your bot's Dockerfile (current directory in this example)
    container_name: nano-bot
    networks:
      - nano-network
    depends_on:
      - nano-pg
    env_file: .env
    environment:
    - TZ=Europe/Paris  # Set the timezone to Paris


  # PostgreSQL Service
  nano-pg:
    image: postgres
    container_name: nano-pg
    networks:
      - nano-network
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Load from .env
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
volumes:
  postgres-data: 
networks:
  nano-network:
    driver: bridge
